### ISSUE TITLE
MySQL issue after update

### ISSUE THREAD

**Issue by wazowski78** [yTakkar/Instagram-clone#24]
Hi my friend,
I think I have some troubles after some updates, can you tell me the MySQL server version you are using please? I think all my problems comes since CPanel autoupdated my servers :(
Thank you.

**Comment by yTakkar** [comment]
My MySQL server version: 10.1.19-MariaDB - mariadb.org binary distribution

**Comment by wazowski78** [comment]
I have some problems, I think they are regarding the servers configurations, look:

```
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Undefined index: u in /Applications/MAMP/htdocs/cbsdk/profile.php on line 38
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 52
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:33 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Undefined offset: 0 in /Applications/MAMP/htdocs/cbsdk/config/class/avatar.class.php on line 20
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 59
[31-Aug-2017 14:20:34 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'get FROM login WHERE user_id = NULL LIMIT 1' at line 1 in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php:110
Stack trace:
#0 /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php(110): PDOStatement->execute(Array)
#1 /Applications/MAMP/htdocs/cbsdk/ajaxify/profile/profile_banner.php(89): universal->isOnline(NULL)
#2 /Applications/MAMP/htdocs/cbsdk/profile.php(76): include_once('/Applications/M...')
#3 {main}
  thrown in /Applications/MAMP/htdocs/cbsdk/config/class/universal.class.php on line 110
```

**Comment by wazowski78** [comment]
The problem with 'u' is in the line of $_GET['u'] from URL, but it is not there...

**Comment by wazowski78** [comment]
So the home page loads, but when I try to press in my profile or any other profile the web shows the no_user or 404 error page.

**Comment by wazowski78** [comment]
I am looking for an issue with the hatches file. Because when I put manually this url: 

http://localhost/cbsdk/profile.php?u=diego 

The page loads well, these problems are in profile page and its descendants, I mean, bookmarks, favorites, images, etc

I need to know how I can change the htaccess or the code that uses the profile page.

**Comment by yTakkar** [comment]
It's a DB connection problem, I think!!

**Comment by wazowski78** [comment]
Nope! I think it is other thing, look, if I use the url:
`http://localhost/cbsdk/profile.php?u=diego`
It seems to work, but if I use the default url:
`http://localhost/cbsdk/profile/diego`
It does not work.

So I have a lot of problems because the profile view is used all along a lot of sections. For example when I want to get access to the photos from the left navigation menu, I get the url:
`http://localhost/cbsdk/profile/diego?ask=photos`
and it does not work, I would need something like:
`http://localhost/cbsdk/profile.php?u=diego&ask=photos`
but this url does not work, can you help me with a working url, how can I get the same result with another one. I am stacked at the ask parameter. How can I call it from a link?

**Comment by yTakkar** [comment]
Ohh, that's a problem with .htaccess file.
It will work with .htaccess file of this repo!!

**Comment by wazowski78** [comment]
I have checked several times, I am using your htaccess file. But I can not figure out what is going wrong with it :(

**Comment by yTakkar** [comment]
Try to install/setup the project again

**Comment by wazowski78** [comment]
I have done it several times too.

**Comment by wazowski78** [comment]
I still thinking is a problem with the htaccess file, I mean, the:
`RewriteRule ^profile/ profile.php [QSA,NC,L]`
seems to work fine, but:
`RewriteRule ^profile/([a-zA-Z0-9._@\-]+)$ profile.php?u=$1 [QSA,NC,L]`
does not work.

**Comment by yTakkar** [comment]
I googled and checked your problem several times and couldn't get the solution!!

**Comment by wazowski78** [comment]
I know, I have tested several times restarting the server, and nothing... The only thing I can do is to revert the links and try to make them work without the htaccess shortcuts. Can you give me some support for that, I am trying to make the left nav photos section work, but I can not figure out how to do make the 'ask' request without the htaccess shortcut.

**Comment by irwandj** [comment]
Hi @wazowski78 and @yTakkar , I have the same issue.
I still cannot figure out how to fix it. 
I can't see any log info to debug the rewriterules, even by adding `LogLevel debug rewrite:trace6` in httpd.conf.
If I find a solution, I will share it here.

**Comment by irwandj** [comment]
Here is the solution : we need to have this line `Options -MultiViews`

The ressource "profile" was always transformed into "profile.php", then the RewriteRule never applied. 

More explanation [here](https://stackoverflow.com/questions/25423141/what-exactly-does-the-the-multiviews-options-in-htaccess).
