### ISSUE TITLE
unable to login & sign up

### ISSUE THREAD

**Issue by nk932714** [yTakkar/Instagram-clone#40]
1) Unable to sign up
then i go to insta official site and signed up
2) Unable to sign in
after creating my account i am unable to sign in see screenshot below  

![image](https://user-images.githubusercontent.com/29853208/31001495-d240b282-a501-11e7-9ea8-3d67137b00ed.png)

**Comment by yTakkar** [comment]
I know why you got that error.
After submit the form, open `console`  and see the error.
If form is submitted to `faiyaz/Instagram/....` then have a look at this link https://github.com/yTakkar/Instagram-clone#loginsignup-error

**Comment by nk932714** [comment]
no error is displaying ; before there was an error of SQL but i fixed that there was wrong password; but now no error is displaying and after  clicking on sign in "sign in button fades and nothing happens.
**EDIT**
i tried on Chrome, Mozilla & IE
Hosted php on Hostinger

**Comment by yTakkar** [comment]
If there's no error in the console, then have a look at these links
https://github.com/yTakkar/Instagram-clone#requirements
https://github.com/yTakkar/Instagram-clone/issues/3#issuecomment-304709493

**Comment by nk932714** [comment]
i missed the .htaccess step i updated the my root dir. 
My instagram folder disappeared. 

i will try again ! 
and thank you very much bro for quick reply

**Comment by nk932714** [comment]
i missed the .htaccess step now follwing error is dispalying 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@main-hosting.eu to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by nk932714** [comment]
Error Log<br>
**/instagram/config/class/login.class.php(155): PDOStatement->execute(Array)
/instagram/ajaxify/ajax_requests/u_checker_requests.php(11): login_class->usernameChecker('nk932714')
{main}
  thrown in/instagram/config/class/login.class.php on line 155
[29-Sep-2017 04:55:46 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected' ininstagram/config/class/login.class.php:77
Stack trace:**

**Comment by nk932714** [comment]
Latest log

[29-Sep-2017 04:40:58 UTC] PHP Fatal error:  Call to a member function prepare() on a non-object in /instagram/config/class/post.class.php on line 608
[29-Sep-2017 04:41:30 UTC] PHP Fatal error:  Call to a member function prepare() on a non-object in /instagram/config/class/post.class.php on line 608
[29-Sep-2017 04:44:54 UTC] PHP Fatal error:  Call to a member function prepare() on a non-object in /instagram/config/class/post.class.php on line 608
[29-Sep-2017 04:55:24 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected' in /instagram/config/class/login.class.php:155
Stack trace:
#0 instagram/config/class/login.class.php(155): PDOStatement->execute(Array)
#1 instagram/ajaxify/ajax_requests/u_checker_requests.php(11): login_class->usernameChecker('nk')
#2 {main}
  thrown in /instagram/config/class/login.class.php on line 155
[29-Sep-2017 04:55:24 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected' in /instagram/config/class/login.class.php:155
Stack trace:

**Comment by yTakkar** [comment]
That's your problem. Something's wrong with your DB configuration!!

**Comment by nk932714** [comment]
ok i will check again

**Comment by krvam** [comment]
u can solve the problem? i have the same problem :( i cant solve
